trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'AzureStudentConnection'  
  resourceGroup: 'etl-demo-rg'
  dataFactoryName: 'health-etl-factory'
  sqlServerName: 'iman-sqlserver'
  sqlDatabaseName: 'SalesDB'
  sqlAdminUsername: 'CloudSA0cbd5e9b'
  sqlAdminPassword: '$(sqlAdminPassword)'  

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az datafactory pipeline create --factory-name $(dataFactoryName) --resource-group $(resourceGroup) --name LoadSalesToStaging --pipeline "@adf/pipeline.json"

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureSubscription)
    ScriptType: 'FilePath'
    ScriptPath: 'scripts/deploy_sql.ps1'
    azurePowerShellVersion: 'LatestVersion'
